server:
  port: 8080

spring:
  config:
    activate:
      on-profile: "dev"

    # DB - MariaDB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/jinius?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none        # none, create, create-drop, update, validate
    defer-datasource-initialization: true
    open-in-view: false
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always

  #redis
  data:
    redis:
      host: ${REDIS_SERVER_IP}
      port: ${REDIS_SERVER_PORT}
      password: ${REDIS_SERVER_PASSWORD}

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace