INSERT INTO TB_USER(POINT) VALUES ( 10000 );
INSERT INTO TB_USER(POINT) VALUES ( 200000 );

INSERT INTO TB_ITEM(ITEM_NAME, ITEM_PRICE, STOCK_QUANTITY) VALUES ('바람막이', 49900, 30);
INSERT INTO TB_ITEM(ITEM_NAME, ITEM_PRICE, STOCK_QUANTITY) VALUES ('청자켓', 59900, 30);
INSERT INTO TB_ITEM(ITEM_NAME, ITEM_PRICE, STOCK_QUANTITY) VALUES ('아노락', 40000, 30);
INSERT INTO TB_ITEM(ITEM_NAME, ITEM_PRICE, STOCK_QUANTITY) VALUES ('블루종', 39900, 30);
INSERT INTO TB_ITEM(ITEM_NAME, ITEM_PRICE, STOCK_QUANTITY) VALUES ('후드티', 50000, 30);
INSERT INTO TB_ITEM(ITEM_NAME, ITEM_PRICE, STOCK_QUANTITY) VALUES ('반팔티', 20000, 30);
INSERT INTO TB_ITEM(ITEM_NAME, ITEM_PRICE, STOCK_QUANTITY) VALUES ('슬랙스', 45000, 30);
INSERT INTO TB_ITEM(ITEM_NAME, ITEM_PRICE, STOCK_QUANTITY) VALUES ('카고', 33000, 30);
INSERT INTO TB_ITEM(ITEM_NAME, ITEM_PRICE, STOCK_QUANTITY) VALUES ('조거팬츠', 48000, 30);
INSERT INTO TB_ITEM(ITEM_NAME, ITEM_PRICE, STOCK_QUANTITY) VALUES ('셋업', 100000, 30);
INSERT INTO TB_ITEM(ITEM_NAME, ITEM_PRICE, STOCK_QUANTITY) VALUES ('양말', 3000, 100);