services:
  redis:
    build: .
    container_name: local_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/opt/homebrew/etc/redis.conf
    restart: always
    command: redis-server /opt/homebrew/etc/redis.conf
